#ifndef WIFI_WONDERS_P2P_EVENTS_H
#define WIFI_WONDERS_P2P_EVENTS_H

enum P2PEvent {
    FIND_STARTED,
    FIND_STOPPED,
    DEVICE_FOUND,
    DEVICE_LOST,
    GROUP_STARTED,
    GROUP_FINISHED,
    GROUP_FORMATION_FAILURE,
    PEER_JOINED,
    PEER_DISCONNECTED,
    P2P_GO_NEGOTIATION_REQUEST,
    P2P_GO_NEGOTIATION_SUCCESS,
    P2P_GO_NEGOTIATION_FAILURE,
    P2P_GROUP_FORMATION_FAILURE,
    PROVISION_DISCOVERY_REQUEST
};

enum P2PEventParamName {
    MAC_ADDRESS,
    DEVICE_NAME,
    GROUP_NAME,
    GROUP_ROLE,
    REASON
};

#endif //WIFI_WONDERS_P2P_EVENTS_H
